---
stages:
  - build
  - upload

variables:
  PPATH: /go/src/github.com/smartsdk

image: golang

before_script:
  - mkdir -p $PPATH
  - ln -s $CI_PROJECT_DIR $PPATH/docker-machine-driver-fiwarelab

build:
  stage: build
  script:
    - cd $PPATH/docker-machine-driver-fiwarelab && make release
  artifacts:
    paths:
      - compile_artifacts

upload:
  stage: upload
  script:
  - ./.uploader
